### ISSUE TITLE
[question] Is appium-idb used by default in appium?

### ISSUE THREAD

**Issue by sirghi** [appium/appium-idb#31]
I've searched the internet for a clear answer to no avail.

Is `appium-idb` an alternative to `appium-ios-device` or `libimobiledevice`, or are they complementary? I'm using `appium` version 1.17.0. Is `appium-idb` used by default in it to communicate with iOS devices and simulator, or you have to set a flag somewhere for it to be used?

Any insight on these aspects would be helpful, as I seem to lack some understanding of the inner workings of Appium, and all its submodules related to iOS.

**Comment by KazuCocoa** [comment]
`launchWithIDB` allows xcuitest-driver to install WDA via idb, but it defaults to `false`.
Geolocation for simulator also uses idb as one of methods.

**Comment by sirghi** [comment]
Thanks. And is there anywhere we can specify it? (Looked through all the capabilities but haven't found anything)

**Comment by KazuCocoa** [comment]
No. The geolocation method has 3 ways. It tries them one by one until they succeed. idb is in the 2nd way.

**Comment by sirghi** [comment]
Sorry, I meant about `launchWithIDB `

**Comment by KazuCocoa** [comment]
That was only addressed in changelog.
I've created a PR to add it https://github.com/appium/appium-xcuitest-driver/pull/1206

**Comment by sirghi** [comment]
Grand. Thanks for that.
