### ISSUE TITLE
How do i start Webdriveragent using fb-idb or appium-idb?

### ISSUE THREAD

**Issue by krishtoautomate** [appium/appium-idb#40]
Original command : xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination  “platform=iOS,id=$UDID test

How do i execute Webdriveragent using fb-idb or appium-idb?

**Comment by KazuCocoa** [comment]
I haven't tried, but I assume `appium:launchWithIDB` capability launches it via idb.
https://github.com/appium/appium-xcuitest-driver
